"""initial schema

Revision ID: 2e4e477b82bf
Revises: 
Create Date: 2026-05-27 20:42:41.013425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = '2e4e477b82bf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('style_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tone', sa.String(length=100), nullable=True),
    sa.Column('pacing', sa.String(length=100), nullable=True),
    sa.Column('avg_sentence_length', sa.Float(), nullable=True),
    sa.Column('common_hooks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('common_ctas', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('narrative_patterns', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('do_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('avoid_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('techniques',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('videos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_url', sa.String(length=2000), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('creator_name', sa.String(length=200), nullable=True),
    sa.Column('niche', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'TRANSCRIBING', 'ANALYZING', 'EMBEDDING', 'DONE', 'ERROR', name='video_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transcript_segments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('position_percent', sa.Float(), nullable=False),
    sa.Column('embedding', Vector(1536), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('script_beats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('segment_id', sa.UUID(), nullable=True),
    sa.Column('beat_type', sa.Enum('HOOK', 'SETUP', 'CONFLICT', 'ESCALATION', 'PAYOFF', 'CTA', name='beat_type'), nullable=False),
    sa.Column('attention_goal', sa.Text(), nullable=True),
    sa.Column('curiosity_question', sa.Text(), nullable=True),
    sa.Column('retention_function', sa.Text(), nullable=True),
    sa.Column('emotion', sa.String(length=100), nullable=True),
    sa.Column('intensity_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['segment_id'], ['transcript_segments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('segment_techniques',
    sa.Column('segment_id', sa.UUID(), nullable=False),
    sa.Column('technique_id', sa.UUID(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['segment_id'], ['transcript_segments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['technique_id'], ['techniques.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('segment_id', 'technique_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('segment_techniques')
    op.drop_table('script_beats')
    op.drop_table('transcript_segments')
    op.drop_table('videos')
    op.drop_table('techniques')
    op.drop_table('style_profiles')
    op.execute("DROP EXTENSION IF EXISTS vector")
    # ### end Alembic commands ###
