"""add view_count and like_count to videos

Revision ID: e44da0f3b0e3
Revises: 2e4e477b82bf
Create Date: 2026-05-28 17:07:21.441550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e44da0f3b0e3'
down_revision: Union[str, None] = '2e4e477b82bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('view_count', sa.Integer(), nullable=True))
    op.add_column('videos', sa.Column('like_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'like_count')
    op.drop_column('videos', 'view_count')
    # ### end Alembic commands ###
